services:
  - type: web
    name: cinematch-backend
    env: node
    plan: free
    buildCommand: npm install && npm --prefix server install
    startCommand: npm --prefix server start
    apiKey: $GCP_API_KEY
    envVars:
      - key1:PORT
        value1:5000
      - key2:DB_HOST
        value2:localhost
      - key3:DB_USER
        value3:root
      - key4 :B_PASSWORD
        value4:root
      - key5:DB_NAME
        value5:cinematch
      - key6:DB_PORT
        value6:3306
      - key7:JWT_SECRET
        value7:cinematch_super_secret_secret
      - key8:TMDB_API_KEY
        value8:f7f4fea187e43720972be14e61291cd2
      - key9:GEMINI_API_KEY
        value9:AQ.Ab8RN6LG4PLQ7sE16HOmK8KimLe6KyPZ-AkEm_rXSskpJ8YySg
      - key10:FRONTEND_URL
        value10:movie-hub-delta-virid.vercel.app

      