services:
  - type: web
    name: cinematch-backend
    env: node
    plan: free
    buildCommand: npm install && npm --prefix server install
    startCommand: npm --prefix server start
    envVars:
      - key: PORT
        value: 5000
      - key: DB_HOST
        value: localhost
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: root
      - key: DB_NAME
        value: cinematch
      - key: DB_PORT
        value: 3306
      - key: JWT_SECRET
        value: change_me
      - key: TMDB_API_KEY
        value: f7f4fea187e43720972be14e61291cd2
      - key: GEMINI_API_KEY
        value: AQ.Ab8RN6LG4PLQ7sE16HOmK8KimLe6KyPZ-AkEm_rXSskpJ8YySg
      - key: FRONTEND_URL
        value: https://your-frontend-domain
